//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxDBEntities : DbContext
    {
        public TaxDBEntities()
            : base("name=TaxDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Автомобиль> Автомобиль { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Класс> Класс { get; set; }
        public virtual DbSet<ЛичныеДанные> ЛичныеДанные { get; set; }
        public virtual DbSet<ОтчетПоАвтомобилю> ОтчетПоАвтомобилю { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Стоянка> Стоянка { get; set; }
        public virtual DbSet<ТипАвтомобиля> ТипАвтомобиля { get; set; }
    }
}
