//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобиль
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Автомобиль()
        {
            this.Заказы = new HashSet<Заказы>();
            this.ОтчетПоАвтомобилю = new HashSet<ОтчетПоАвтомобилю>();
        }
    
        public int Айди { get; set; }
        public int АйдиТипаАвтомобиля { get; set; }
        public int АйдиКласса { get; set; }
        public string ГосНомер { get; set; }
    
        public virtual Класс Класс { get; set; }
        public virtual ТипАвтомобиля ТипАвтомобиля { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОтчетПоАвтомобилю> ОтчетПоАвтомобилю { get; set; }
    }
}
