//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int Айди { get; set; }
        public int АйдиСотрудника { get; set; }
        public int АйдиАвтомобиля { get; set; }
        public int АйдиКласса { get; set; }
        public string Откуда { get; set; }
        public string Куда { get; set; }
        public string Комментарий { get; set; }
    
        public virtual Автомобиль Автомобиль { get; set; }
        public virtual Класс Класс { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
