//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ОтчетПоАвтомобилю
    {
        public int Айди { get; set; }
        public System.DateTime Дата { get; set; }
        public int АйдиАвтомобиля { get; set; }
        public int АйдиСтоянки { get; set; }
    
        public virtual Автомобиль Автомобиль { get; set; }
        public virtual Стоянка Стоянка { get; set; }
    }
}
